### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [itmammoth/pysync#4]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary itm-pysync -w /tmp/ext itm-pysync==1.0.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting itm-pysync==1.0.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/bdb/6c4a19754883d/itm.pysync-1.0.0.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-9v_uhzqd/itm-pysync/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-9v_uhzqd/itm-pysync/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-9v_uhzqd/itm-pysync/pip-egg-info
         cwd: /tmp/pip-wheel-9v_uhzqd/itm-pysync/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-9v_uhzqd/itm-pysync/setup.py", line 31, in <module>
        install_requires=open('requirements.txt').read().splitlines(),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by itmammoth** [comment]
The following command works for you?
```
$ pip install itm.pysync
```

**Comment by thatch** [comment]
```
pip install itm.pysync # works, installs the wheel and does not execute setup.py
pip install --no-binary itm-pysync itm.pysync # does not work, because the sdist is missing some files
```

I just sent a pr that should fix this.

**Comment by itmammoth** [comment]
Thx
Please try with version 1.0.1

**Comment by thatch** [comment]
Version 1.0.1 works great!
